<?php
require_once 'PHPUnit/Framework.php';

require_once '../ipenumerator.php';

/**
 * Test class for ipenumerator.
 * Generated by PHPUnit on 2010-06-05 at 10:43:36.
 */
class ipenumeratorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    ipenumerator
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

	public function testNetwork()
	{
		$cidr = '192.168.1.8/30';

		$ipenum = new IpEnumerator($cidr);

		$result = $ipenum->network();
		$expected = "192.168.1.8";
		$this->assertEquals($expected, $result);
	}

	public function testBroadcast()
	{
		$cidr = '192.168.1.8/30';

		$ipenum = new IpEnumerator($cidr);

		$result = $ipenum->broadcast();
		$expected = "192.168.1.11";
		$this->assertEquals($expected, $result);
	}

	public function testIps()
	{
		$cidr = '192.168.1.8/30';

		$ipenum = new IpEnumerator($cidr);
		$result = array();
		foreach ($ipenum as $ip) {
			$result[] = $ip;
		}

		$expected = array(
			"192.168.1.8",
			"192.168.1.9",
			"192.168.1.10",
			"192.168.1.11",
		);
		$this->assertEquals($expected, $result);
	}
}
